# Generated by Django 4.2.4 on 2023-09-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_owner_alter_auctionlisting_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='starting_bid',
            new_name='bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='price',
        ),
    ]
