# Generated by Django 4.2.4 on 2023-09-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_owner_alter_bid_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='price',
        ),
    ]
