# Generated by Django 4.2.4 on 2023-09-07 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_bid_bid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commenter_name',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder_name',
            field=models.ManyToManyField(blank=True, related_name='bidder_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_name',
            field=models.ManyToManyField(blank=True, related_name='commenter_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
