# Generated by Django 4.2.4 on 2023-09-07 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_bid_bidder_name_remove_comment_commenter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder_name',
            field=models.ManyToManyField(blank=True, related_name='bid_action', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter_name',
            field=models.ManyToManyField(blank=True, related_name='comment_action', to=settings.AUTH_USER_MODEL),
        ),
    ]
