# Generated by Django 4.2.4 on 2023-09-07 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_bidder_name_alter_comment_commenter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commenter_name',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid_action', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_action', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
