# Generated by Django 4.2.4 on 2023-09-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_bid_bidder_name_remove_comment_commenter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
