# Generated by Django 4.2.4 on 2023-09-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlisting_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
