# Generated by Django 4.2.4 on 2023-09-10 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auctionlisting_winner_alter_auctionlisting_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.auctionlisting')),
                ('watcher', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_action', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
