# Generated by Django 4.2.4 on 2023-09-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to='auctions.auctionlisting'),
        ),
    ]
