# Generated by Django 4.2.4 on 2023-09-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_watchlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='is_added_to_watchlist',
            field=models.BooleanField(null=True),
        ),
    ]
