# Generated by Django 4.2.4 on 2023-09-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_remove_watchlist_product_watchlist_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='product',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to='auctions.auctionlisting'),
        ),
    ]
