# Generated by Django 4.2.4 on 2023-09-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_remove_watchlist_product_watchlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='is_added_to_watchlist',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
