# Generated by Django 4.2.4 on 2023-09-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_auctionlisting_is_added_to_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='is_added_to_watchlist',
        ),
    ]
