# Generated by Django 4.2.4 on 2023-09-11 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_remove_auctionlisting_is_added_to_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watcher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_action', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.auctionlisting')),
            ],
        ),
    ]
