# Generated by Django 4.2.4 on 2023-09-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_remove_auctionlisting_category_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.auctionlisting'),
        ),
    ]
