# Generated by Django 4.2.4 on 2023-09-13 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_remove_watchlist_product_watchlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_action', to=settings.AUTH_USER_MODEL),
        ),
    ]
